# Generated by Django 6.1 on 2026-08-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Interested', 'Interested'), ('Not Interested', 'Not Interested'), ('No Answer', 'No Answer'), ('Call Back Later', 'Call Back Later'), ('Wrong Number', 'Wrong Number')], max_length=20)),
                ('priority', models.CharField(choices=[('Hot', 'Hot'), ('Warm', 'Warm'), ('Cold', 'Cold')], max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('followup_date', models.DateField(blank=True, null=True)),
                ('followup_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
