# Generated by Django 6.1 on 2026-08-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadactivity',
            name='recording',
            field=models.FileField(blank=True, null=True, upload_to='recordings/%Y/%m/'),
        ),
    ]
